### ISSUE TITLE
Does it feature multi users or OAuth2?

### ISSUE THREAD

**Issue by nhh** [EsperoTech/yaade#1]
Hi 👋

I would like to find out if yaade supports mutiple users, and/or does it have single sign on capabilities?

I would like to install it in our company network and share requests/responses for different users and customer projects!

Thank you for you work!

Greetings
Niklas

**Comment by jonrosner** [comment]
Hi,

multi-users is one of the features on top of the roadmap. OAuth will need a little bit more planning. How would you like to use OAuth? How do you see yourself setting user permissions when using OAuth? Does your company have fixed roles or user groups in its OAuth tokens?

**Comment by nhh** [comment]
Hi,

Yeah basically we have users and roles inside a token.

It would be great if you dpnt need to administer users inside yaade.

In our case we have centralized user managament with keycloak and integrating several services with it.

**Comment by firestrife23** [comment]
Likewise, and I use [Authentik](http://goauthentik.io)

**Comment by jonrosner** [comment]
Yaade now supports multi users management. OAuth2 support will follow next

**Comment by alexanderadam** [comment]
> OAuth2 support will follow next

Is there another GitHub issue to track OAuth2 support?

**Comment by jonrosner** [comment]
@alexanderadam please open another issue and i will keep you updated there

**Comment by jonrosner** [comment]
For readers that do not follow the other issue: OIDC and OAuth is now implemented. Refer to this issue for some example configuration: https://github.com/EsperoTech/yaade/issues/7

An exhaustive documentation will follow.
