### ISSUE TITLE
BUG report：Error when compiling jar package

### ISSUE THREAD

**Issue by cloudGrin** [EsperoTech/yaade#108]
My computer is a mac m1 chip. I have installed java11 and kotlin. When running ./gradlew clean assemble local compilation, the following error occurred.

yaade/server/src/main/java/org/openapitools/codegen/examples/ExampleGenerator.java uses unchecked or unsafe operations.
NOTE: For more information, recompile with -Xlint:unchecked.

![image](https://github.com/EsperoTech/yaade/assets/27754342/298be153-9bf7-4341-9783-acefab5a3db2)

**Comment by jonrosner** [comment]
The build itself is successful. This is just a warning, you can safely ignore it.

**Comment by cloudGrin** [comment]
Thank you for your answer, this is my first time running a java project.

I am a front-end developer. Since I have not installed java and kotlin locally, when I wanted to package locally today, I wrote a Dockfile to install java and kotlin for compiling the jar package, but when I executed RUN ./gradlew clean assemble When executing the command, it got stuck. I waited for 20 minutes and it was still stuck without any log output. I don’t know why. Can you please help me solve this problem? I look forward to your answer.

The following is my Dockfile

`FROM openjdk:11 as first

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl zip unzip && \
    curl -s "https://get.sdkman.io" | bash && \
    bash -c "source /root/.sdkman/bin/sdkman-init.sh && sdk install kotlin" && \
    rm -rf /var/lib/apt/lists/*

COPY . .
RUN ./gradlew clean assemble

FROM amazoncorretto:11

RUN mkdir /app

COPY --from=first /app/build/libs/yaade-server-1.0-SNAPSHOT.jar /app/yaade.jar

EXPOSE 9339

CMD ["java", "-jar", "/app/yaade.jar"]`

**Comment by jonrosner** [comment]
will close due to inactivity
