### ISSUE TITLE
Feature request: re-order collection and requests

### ISSUE THREAD

**Issue by jghaanstra** [EsperoTech/yaade#12]
I really like Yaade. Something basic I'm missing though is being able to re-order the collections and requests. This helps me keep stuff organized.

**Comment by jonathan-roesner** [comment]
Hello,

I am very glad you enjoy Yaade. Reordering using drag and drop is definitely on the roadmap and will be coming soon! I will keep you updated in this issue once the feature is merged.

JR

**Comment by binaryfire** [comment]
I'll also add a request for subfolders within a collection. That's a must for keeping things organised.

**Comment by jonrosner** [comment]
After more time than expected, I can finally say that reordering collections made it into Yaade :+1:

Check out the docs on how to update: https://docs.yaade.io/getting-started.html

**Comment by jghaanstra** [comment]
This is awesome, it works great. Thanx.
