### ISSUE TITLE
Secrets not work. 

### ISSUE THREAD

**Issue by popescuvitor** [EsperoTech/yaade#133]
When I make a request by passing a secret according to the documentation, the secret is not being converted.

Respondendo ao cliente...
192.168.96.2 - - [30/Jan/2024 14:05:49] "GET / HTTP/1.1" 200 -
Headers da Solicitação GET:
user-agent: Vert.x-WebClient/4.5.1
Authorization: somesome:$S{secretKey}

![Screenshot from 2024-01-30 14-15-19](https://github.com/EsperoTech/yaade/assets/116237324/791d6dda-3411-42c1-ad75-05c78fc8ae6f)

**Comment by jonrosner** [comment]
Is the secret correctly defined in your environment that you selected? Secrets only work using the server proxy.

**Comment by popescuvitor** [comment]
Yes, it is!
![image](https://github.com/EsperoTech/yaade/assets/116237324/01c5641d-7a3b-4a5f-8ea2-572c7c48d71d)

**Comment by jonrosner** [comment]
Thanks for pointing this out. Can reproduce the bug. I will fix it and push a bugfix asap.

**Comment by popescuvitor** [comment]
You're welcome, thank you very much for the response, and congratulations on the project. Whenever possible, I will try to contribute.

**Comment by jonrosner** [comment]
I pushed a fix and released it to the nightly branch.

You can test it by running

```
docker run -d --restart=always -p 9339:9339 \
    -e YAADE_ADMIN_USERNAME=admin -v yaade:/app/data \
    --name yaade esperotech/yaade:nightly
```

Tell me if it solves the problem for you.

**Comment by popescuvitor** [comment]
It worked, congratulations! You're really awesome!
