### ISSUE TITLE
Variables feature on Body doesnt work

### ISSUE THREAD

**Issue by pmoraitopoulos** [EsperoTech/yaade#136]
when i use the variables in the URL it interpolate it.
when i use the variables in the body. it doesnt change to its value. 
![image](https://github.com/EsperoTech/yaade/assets/29717793/77eaa6a0-3cc8-4f54-b7ef-c3f4711958bc)
![image](https://github.com/EsperoTech/yaade/assets/29717793/36a06657-51f8-483e-899a-7ad71c318dd5)

**Comment by jonrosner** [comment]
I can't replicate your issue. Are you running the latest version of Yaade? Try

```
docker rm -f yaade
docker pull esperotech/yaade:latest
docker run -d --restart=always -p 9339:9339 \
    -e YAADE_ADMIN_USERNAME=admin -v yaade:/app/data \
    --name yaade esperotech/yaade:latest
```

If that doesn't solve the issue please create a minimal reproducible example by starting a fresh instance and posting the steps to reproduce.

**Comment by pmoraitopoulos** [comment]
Now that i put the latest variables and secrets doesnt work at all. i have installed Yaade on synology Nas with docker.
i run this

docker run -d --name=yaade \
-p 9339:9339 \
-e YAADE_ADMIN_USERNAME=pmoraitopoulos \
-v /volume1/docker/yaade:/app/data \
--restart always \
esperotech/yaade:latest

then i enter and there was an empty collection. i add new environment and a variable.

![image](https://github.com/EsperoTech/yaade/assets/29717793/595a731c-22fa-4dd1-b29e-72c4d77d57c5)

![image](https://github.com/EsperoTech/yaade/assets/29717793/50dc226a-1dd7-41b3-b992-becba3cf1957)

![image](https://github.com/EsperoTech/yaade/assets/29717793/341e89d6-899a-4e5a-ae05-d19cfce81d0f)
![image](https://github.com/EsperoTech/yaade/assets/29717793/ed3b0728-07cb-4b78-8c82-b9baa424a5f1)

**Comment by jonrosner** [comment]
I followed the same steps and I cannot reproduce it.

Here are some other debugging suggestions:

Explicitly run `docker pull esperotech/yaade:latest` before starting the container

Try manually saving both the collection and request (top right is a save button) and then refresh the page.

**Comment by pmoraitopoulos** [comment]
Hello,

For your information, after restart the container, i had an issue.
I have a variable for a url and i use it in the URL as post.
I clicked on send button and error occur (something like ${url} could not resolve after 2 queries. 
I go to the environments of the collection, i put a dot in the variable. i click save manually. Again i delete the dot from the variable url and i clicked save manually. it fixes the error.
