### ISSUE TITLE
Patch not send body?

### ISSUE THREAD

**Issue by DenisVASI9** [EsperoTech/yaade#141]
![Screenshot from 2024-03-18 11-39-37](https://github.com/EsperoTech/yaade/assets/48092110/9ac098d9-9bbe-4d66-ab13-262b74e3e009)

**Comment by jonrosner** [comment]
Please create a minimal reproducible example with all the necessary components. I can't reproduce this with my own services and patch endpoints.

**Comment by DenisVASI9** [comment]
@jonrosner okay, do you have telegram? I can't give my public api here.

**Comment by jonrosner** [comment]
If you want to get help here you will have to provide a minimal reproducible example. That means you have to create a github repository that contains a server that mimics your own (e.g. a small node.js express server) where this problem occurs as well.

**Comment by DenisVASI9** [comment]
@jonrosner 
I could give you the endpoint and data in private messages. I can certainly create a repository, but it won't be the same code as my production. He's using a white ip

**Comment by jonrosner** [comment]
If you cannot reproduce it with a clean minimal server then the issue is not coming from Yaade, but of your server and we cannot help you fix your own code.

**Comment by DenisVASI9** [comment]
@jonrosner 
https://github.com/DenisVASI9/yaade-patch-problem
![Screenshot from 2024-03-19 10-22-16](https://github.com/EsperoTech/yaade/assets/48092110/3c2cfc4f-84dd-4594-89fa-0e0449cc5eef)

**Comment by jonrosner** [comment]
Thank you for providing the example. This is not a Yaade problem, but a nest.js problem. You are missing the `Content-Type: application/json` header when sending the request. Nest doesn't seem to inform you about this and interprets the body as some unknown type and thus cannot find your specified values.
