### ISSUE TITLE
Feature Request: Make web->extension timeout configurable

### ISSUE THREAD

**Issue by wolfgang-braun** [EsperoTech/yaade#142]
Hi,

really great tool! 

The extension is able to handle long running requests. However the web app timeouts early.
What do you think about making the hard coded 5 seconds configurable?

https://github.com/EsperoTech/yaade/blob/25d821ded0e577bd4b13420310664e37a49d901e/client/src/components/requestPanel/RequestSender.tsx#L355-L359

Thank you!

**Comment by jonrosner** [comment]
Hi,

great idea. Will add it the backlog.

**Comment by pbach-tiplu** [comment]
@jonrosner We'd love to see that feature too! The docker container is awesome, and we'd love to use yaade, but we're hindered by this short hardcoded timeout.

**Comment by jonrosner** [comment]
this is now configurable on a collection level.
