### ISSUE TITLE
mTLS/Client Certificate Authentication

### ISSUE THREAD

**Issue by scheibling** [EsperoTech/yaade#143]
I'd love to revisit the topic brought up in #26, mTLS Authentication/Client Certificates.
A lot of the APIs I work with, both internal and external, are using some kind of mutual TLS authentication to be able to send requests, meaning you'll add a certificate bundle (pfx or combined pem) for all connections for a specific URL, either globally, per workspace or per collection.

For a reference, both Postman, Bruno and Insomnia have implementations for this. An alternative for their implementation would be the ability to add certificates via the scripting functionality

I'd be happy to help out on the frontend parts, but my knowledge in Kotlin is very limited unfortunately

**Comment by jonrosner** [comment]
As of my understanding you should be able to manually install your mTLS certificate in your browser and the extension should pick it up automatically. Did you try this?

I have not worked with mTLS myself, so I am no expert in this area so I'd be glad if you could help me out here.

I guess for the server proxy this shouldn't be too difficult to achieve:

1. somehow store the certificate
2. fetch it on every request that is done via the server proxy
3. configure the vert.x web client to use this certificate

**Comment by scheibling** [comment]
An update on using the in-browser certificate manager for those requests - that worked for the requests sent via the Plugin, thank you for the idea! You might have to go to the URL manually to select the certificate the first time, but after that the requests went through without issues

**Comment by jonrosner** [comment]
@scheibling the backend part of it is ready. If you want to take over the frontend part it should be fairly simple:

1. Add another config section "Certificates"
2. Add a form with which you can upload a new certificate
3. Send the content of the form to the backend API
4. Have a list that shows existing certificates and a button to delete them

**Comment by scheibling** [comment]
@jonrosner gracias, I'll have a look at it during the week :-)

**Comment by jonrosner** [comment]
Thanks to @n14s I was able to finish this one up. You can check it out in the nightly build.
