### ISSUE TITLE
Feature Request: Support body content-type: `application/x-www-form-urlencoded`

### ISSUE THREAD

**Issue by arcastro** [EsperoTech/yaade#146]
The body content-type is currently limited to:
* application/json
* application/xml
* text/html
* text/plain

![image](https://github.com/EsperoTech/yaade/assets/4576794/3c4cf78a-7e3e-4577-b74b-dae2f5c6ba06)

I'm opening this issue to add support for  `application/x-www-form-urlencoded` as well. 
This would be in the format of key-value pairs

Here's a mock of what it could potentially look like,

![image](https://github.com/EsperoTech/yaade/assets/4576794/c2cce36a-c6ca-4ab5-8d1d-8ab83018e6df)

**Comment by jonrosner** [comment]
I see you already found the other issue and PR. The image you posted pretty much resembles how it will look like in the end. I will close this one as a duplicate.
