### ISSUE TITLE
Adding provider failing with error - issuer cannot be null.

### ISSUE THREAD

**Issue by iamsid** [EsperoTech/yaade#150]
Hi.
I have self-hosted yaade on a remote server.
The app is running. While trying to add a provider for external users, it keeps failing with error: `issuer cannot be null`.
I see a huge stack trace in the network tab of browser dev tools for `api/config/auth_config`.

Here's my Keycloak provider configuration:
```
{
    "providers": [{
        "id": "my-sso",
        "label": "Login with SSO",
        "provider": "keycloak",
        "params": {
            "clientId": "yaade",
            "clientSecret": "xxxx",
            "callbackUrl": "https://example.com/keycloak",
            "fields": {
                "username": "/preferred_username",
                "groups": "/groups",
                "defaultGroups": ["test"]
            },
            "scopes": ["openid"]
        }
    }]
}

```

**Comment by jonrosner** [comment]
Hello. It seems like you are missing the site param:

`"site": "https://keycloak.example.com/auth/realms/test"`

See the docs for more help: https://docs.yaade.io/users-groups.html

**Comment by iamsid** [comment]
Ah yes! I had the value prepared when I was reading the doc, but then it skipped my mind.
That works. Authentication is working as well. :)

I see that the default groups assigned in the JSON above is applied to the user logged using provider, but how do I give them access to more groups?
I am not sure if its to be done on Keycloak or yaade.

**Comment by jonrosner** [comment]
hey, unfortunately right now it is not possible to assign more groups to users logging in via oauth2. But it should be possible technically. Please open a feature ticket for this. I'll close this one.
