### ISSUE TITLE
Feature Request: Allow groups to be added and removed for external users.

### ISSUE THREAD

**Issue by iamsid** [EsperoTech/yaade#152]
As identified in #150, users added via external provider (OAuth2, OID) are given access only to default groups.
There is no way to modify that access right now. Please add an option to manage groups for external users, same as local users.. either via the external platform or via yaade.

**Comment by jonrosner** [comment]
you can add groups via the external system. The configuration `fields` section provides you with two configuration options:

1. `fields/groups` which is a JSON Path to your groups in the received user info token.
2. `fields/filter` is a regex that lets you filter those groups.

managing an external user's groups from within Yaade would be possible. I'll investigate this further.
