### ISSUE TITLE
Feature Request: Generate code from requests

### ISSUE THREAD

**Issue by nickian** [EsperoTech/yaade#158]
It would be nice if we could generate code snippets from the requests like [RapidAPI](https://paw.cloud/client) does. They have a dropdown with a list of different clients to generate code for. Even just a few basic types like these would be nice:

- cURL
- Axios
- PHP cURL
- PHP Guzzle
- Python Requests
- Go HTTP

**Comment by jonrosner** [comment]
Merged this into nightly. PHP did not work out of the box though. Not sure how deep I want to dig into here to make it work as the lib uses some really nasty polyfills that might never work... Will close this for now.
