### ISSUE TITLE
Import after Export not working

### ISSUE THREAD

**Issue by pbach-tiplu** [EsperoTech/yaade#159]
I tried the export / import functionality on my docker container. 

I deleted the default Collection and created a new collection with one request that I exported. 
After importing the previous exported db-file, everything was deleted and I only see the default Collection again.

**Comment by jonrosner** [comment]
I cannot replicate this issue.

Steps I did

1. I started a completely fresh Yaade container
2. I deleted the collection
3. I created a new collection and a new request
4. I exported the DB
5. I imported the DB
6. the new collection and request is still there

**Comment by jonrosner** [comment]
closed due to inactivity
