### ISSUE TITLE
Environment not available

### ISSUE THREAD

**Issue by squalou** [EsperoTech/yaade#165]
Hi,

I'm sorry if I miss an obvious thing, but I can't find how to deal with / select environments

From the documentation

```
 Yaade provides a sophisticated environment interpolation system. To create a new environment click ••• > Environment next to the desired collection.
 ```
 
 but I don't see "Environment" in the menu.
 
 I'm running locally, I did try in "local dev" mode or by building a local docker image and running it.
 
 When I use ${something} somewhere, and hover it, it shows me a nice "NO ENV SELECTED" message, which is fine, but I have absolutely no clue as to how to select one.
 
 Once again, I feel stupid asking this, it's probably obvious.
 
 
![image](https://github.com/EsperoTech/yaade/assets/4623644/b128e704-7171-41e5-a698-e007d20d09b8)

**Comment by squalou** [comment]
DAMN

answering myself : looks like you need to *create* environments with an admin user firts.

Once again sorry for the noise

**Comment by Myzel394** [comment]
I'm facing the same issue, how do you create environments first? I think this is very confusing tbh.

**Comment by jonrosner** [comment]
hi @Myzel394 , can you explain what the expected behavior is? How are you supposed to use environment variables without creating an environment first?

**Comment by Myzel394** [comment]
> How are you supposed to use environment variables without creating an environment first?

Yes that's my question: How do you create an environment?

**Comment by jonrosner** [comment]
The docs describw how to create a new env[:](https://docs.yaade.io/environments.html)

**Comment by Myzel394** [comment]
@jonrosner I'm facing the same issue: _Environment not available_. The answer was:

> answering myself : looks like you need to create environments with an admin user first.

How do I do that? That's my question. This doesn't seem to be documented

**Comment by jonrosner** [comment]
you don't need to be an admin user to create an environment. As the documentation states. You click on the collection and in the "Environments" tab, you click the + sign and enter a name. A new environment is created and you can fill it with variables.

**Comment by jonrosner** [comment]
<img width="1009" alt="image" src="https://github.com/EsperoTech/yaade/assets/22355732/c94a2997-93aa-49b5-a5ee-239c09b48583">
