### ISSUE TITLE
Error importing collection

### ISSUE THREAD

**Issue by itguy327** [EsperoTech/yaade#166]
[openapi.txt](https://github.com/EsperoTech/yaade/files/15477334/openapi.txt)
The attached txt file is actually yaml that imports into other programs and generates expected collections (Postman, milkman, Insomnia)

Yaade is throwing an error and partially imports. I'd be thankful for any help as I love Yaade and don't want to use another tool.

Thank you

**Comment by jonrosner** [comment]
thank you for pointing this out. I fixed the issue and released to the nightly branch. Feel free to test it out and open another issue if you find another problem.

**Comment by itguy327** [comment]
SWEET!!

Thank you. Working now
