### ISSUE TITLE
Unable to add group for user + workaround 

### ISSUE THREAD

**Issue by geourjoa** [EsperoTech/yaade#172]
I was unable to add groups for the user with the UI. 

BUG to reproduce : 

- Open admin account 
- Go to Settings / Users / local
- Try to edit a user, write a groupname (for example admin)
- Click on validate 

Nothing work.
I have studied the request sent (https://myYaadeDeploy.com/api/users/9): 

![image](https://github.com/EsperoTech/yaade/assets/122985699/99fb16ac-86a3-49f4-a6ef-b34084c3c91f)

Nothing in the group field.

WORKAROUND 

- Use yaade to hack yaade himself 
- Create a request 
   - PUT https://myYaadeDeploy.com/api/users/9
   - Body : {"id":9,"username":"anthony","version":"1.0.0","data":{"settings":{"saveOnSend":true,"saveOnClose":true},"groups":["admin]}}
 - Send request  
 
 9 is the concerned user id. You can try to edit user and check the request sent to get the id 
 
 
 DEPLOYMENT : 
 - self-hosted 
 - Docker image : https://hub.docker.com/layers/esperotech/yaade/latest/images/sha256-0a03c787cdf1fa9fef7dcd6b6d8ec5d5603bac9bd018e1023c05acc779880508?context=explore

**Comment by jonrosner** [comment]
did you hit spacebar after you input the group?

**Comment by geourjoa** [comment]
Damn it works ... 

It will be much more clear to hit enter to add the group and not space. Or add a tooltip  ...

Anymay thanks for your answer !

**Comment by jonrosner** [comment]
Thanks, will try to make it more clear.
