### ISSUE TITLE
Reset Password

### ISSUE THREAD

**Issue by Fovir-GitHub** [EsperoTech/yaade#175]
Unfortunately, I forgot my password.
Are there any way to reset my password?
I had tried to reinstall it, however, it didn't work.
Thanks for your help.

**Comment by jonrosner** [comment]
Yes this is possible. Given that you used a persistent docker volume as stated in the docs you can remove your currently running container `docker rm -f yaade` and start a new one with a new admin username:

```bash
docker run -d --restart=always -p 9339:9339 \
    -e YAADE_ADMIN_USERNAME=admin2 -v yaade:/app/data \
    --name yaade esperotech/yaade:latest
```

The password for the new admin2 user will be `password`
