### ISSUE TITLE
Sending file in request body

### ISSUE THREAD

**Issue by paulo-hortelan** [EsperoTech/yaade#182]
Is there a way to upload/send a file on the body of the request?

In Postman we have this:
![image](https://github.com/user-attachments/assets/d27fe605-1e6c-4a56-b2dc-d8814c6a2ce6)

This is the only issue preventing me from using Yaade as my oficial API manager

**Comment by jonrosner** [comment]
Thanks for creating this issue. It's on the list of features being worked on.

**Comment by jonrosner** [comment]
Files are now supported in Requests. Download the newest nightly container and upgrade your extension.

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/ebeebadc-e2cf-48b0-96b4-c26b0e96a2bd">

<img width="1198" alt="image" src="https://github.com/user-attachments/assets/7c3f6297-2270-45b3-90a8-99ec756e5c35">

**Comment by paulo-hortelan** [comment]
I did the container upgrade using your tutorial: https://github.com/EsperoTech/yaade?tab=readme-ov-file#%EF%B8%8F-upgrade

But this new feature is not showing, can you give me some light? Should have `multipart/form-data`, correct?

![image](https://github.com/user-attachments/assets/ee5f9a41-b743-4e32-aa11-fdea10e13d84)

**Comment by jonrosner** [comment]
Did you pull the nightly container? `docker pull esperotech/yaade:nightly`

**Comment by paulo-hortelan** [comment]
Oh, my bad. I was pulling from the `latest`. Thank you 👍
