### ISSUE TITLE
No inheritance for collections

### ISSUE THREAD

**Issue by eloraux** [EsperoTech/yaade#183]
Hi, Yaade is deployed with docker in version latest version (1.7.1).

I have collection in collection like this :
![image](https://github.com/user-attachments/assets/05066b98-7051-4986-99f4-537f0cfe867f)

Its very useful for organization by project.
When I put environment variable, headers or whatever in parent collection, the variable is not define in children's collection.

For example i set "DOMAIN" variable for the domain of the entire project

![image](https://github.com/user-attachments/assets/14f0d7ef-1909-439e-8ab8-28c5a7c6b705)

DOMAIN variable is "unknown" in request of  "test one" collection

![image](https://github.com/user-attachments/assets/7983c66e-b341-46a7-bca3-77a91006090e)

I don't know if is bug or feature but but it would be cool and more user frendly to have it.
Best regards,
Elian for Tétras Libre.

**Comment by jonrosner** [comment]
environment inheritance is on the list of features being implemented.

**Comment by fritzdimmel** [comment]
Hi @jonrosner,
any plan when this might be implemented? We also have a huge collection with several sub folders and rely on environment variables heavily that cannot be used now.
Thanks

**Comment by jonrosner** [comment]
This is currently being worked on.

**Comment by jonrosner** [comment]
I just merged this into the nightly branch. Feel free to try it out using `docker pull esperotech/yaade:nightly`
