### ISSUE TITLE
BUG: No past in field

### ISSUE THREAD

**Issue by eloraux** [EsperoTech/yaade#184]
Hi, Yaade is deployed with docker in version latest version (1.7.1).

Its not possible to past anything in fields (environement, header or URI).
In script everything look work good.

It seems to me that the version before the potman import patch (#171) the past work but I am not sure.

This little bug is a little frustrating but the project remains cool!
Best regards,
Elian for Tétras Libre.

**Comment by jonrosner** [comment]
This seems to be a problem with Codemirror and single-line editor. We intercept all input events and remove new lines, but this check basically deletes the history. I did not find a good way to resolve this, yet. If you want you can take a look yourself.

**Comment by jonrosner** [comment]
Thanks to the help of the people at codemirror I found the problem and fixed it. The new :nightly container has an improved single-line-editor!
