### ISSUE TITLE
Restoring backups unwraps nested collections

### ISSUE THREAD

**Issue by n14s** [EsperoTech/yaade#197]
If backups are created that contain collections that are nested, say:

collection 1 > collection 1.1 > collection 1.1.1 > request 1
collection 2 > request 1

restoring that backup results in the unwrapping of the collections, with the result:

collection 1 > -empty-
collection 1.1 > -empty-
collection 1.1.1 > request 1
collection 2 > request 1

**Comment by jonrosner** [comment]
is the container you are using to restore the backup the latest container?

**Comment by n14s** [comment]
Running locally on the latest main (b757...)

**Comment by jonrosner** [comment]
this is the latest image sha: ebe8eebf657b

**Comment by n14s** [comment]
When using docker instead of running dev-client.sh from source code, the import worked as expect. Thanks.
