### ISSUE TITLE
[Feature Request] Add websockets

### ISSUE THREAD

**Issue by montarion** [EsperoTech/yaade#213]
Hi,

First, I love Yaade, it works very well.

Are there any plans to include websocket support? Being able to test that as well would be great.

That would allow me to stop using postman/insomnia/hoppscotch entirely.

**Comment by jonrosner** [comment]
Thank you for the kind words.
I just merged a WebSocket implementation here https://github.com/EsperoTech/yaade/pull/211. It is not very refined yet and the extension update is not approved yet but the whole thing should be ready in a week or two.

**Comment by jonrosner** [comment]
Websockets are now available. You need to download the latest nightly container and upgrade your extension.

**Comment by montarion** [comment]
oh wow that's amazing timing! Thanks you!
