### ISSUE TITLE
ODIC Callback

### ISSUE THREAD

**Issue by firestrife23** [EsperoTech/yaade#22]
OIDC Callback is null? it's not empty cuz i filled it out, see screenshot below

[![Alt text](https://i.imgur.com/wt0xq2l.png)](https://imgur.com/a/UiTo4wx)

**Comment by jonrosner** [comment]
Sorry for the breaking change:

Remove `callback` object and set it to a single string `callbackUrl`.

See: https://docs.yaade.io/users-groups.html#required-oauth2-params

**Comment by firestrife23** [comment]
Thank you
