### ISSUE TITLE
Generate sample request from openapi.yaml 

### ISSUE THREAD

**Issue by n14s** [EsperoTech/yaade#27]
The OpenApi/Swagger UI generates an example request from the example data defined in the openapi.yaml.
It would be awesome if Yaade would do the same.

**Comment by jonrosner** [comment]
This will be there in one of the next releases! We are already working on it.

**Comment by jonrosner** [comment]
I'm glad to tell you that the new release supports generating example bodies for OpenAPI imports!

Have fun.
