### ISSUE TITLE
Some Suggestions

### ISSUE THREAD

**Issue by beeing** [EsperoTech/yaade#4]
Hi team, thanks for this project. I have been looking for awhile on something like this and glad I stumbled on this project.

Would be great tool to use if we can include:
1. documentation for each requests, possibly markdown friendly
2. mock server facility so we can mock and add sample requests

With the above, it can be used as self-hosted stoplight.io

**Comment by jonrosner** [comment]
Thank you for your comment. Could you elaborate a little bit more on that documentation feature. Would a simple tab called "Documentation" where a markdown editor sits be enough?

**Comment by beeing** [comment]
Sorry for being too brief. What I observe on most API documentations have similar structure:

- description - describe what the API does
- request - the inputs such as params, query, headers, body
- response - possible outputs from the API

**Comment by binaryfire** [comment]
@jonrosner I think a simple unopinionated "Documentation" tab using a markdown editor would be perfect, and probably easier to implement too? Fixed fields might be a bit too restrictive for certain use cases.
