### ISSUE TITLE
Add support of basepath

### ISSUE THREAD

**Issue by vchirikov** [EsperoTech/yaade#40]
Didn't find an information about base path variable, do you have this setting?

**Comment by jonrosner** [comment]
Could you give a quick example of how you would want this feature to look and what exactly you mean when you refer to base path variable?

**Comment by jonrosner** [comment]
Thank you for pointing this out. Will be investigated and fixed asap.

**Comment by jonrosner** [comment]
FYI: This is actively worked on and will be featured in the next release

**Comment by jonrosner** [comment]
Fixed in the newest version. To use it, simply add the environment variable `-e YAADE_BASE_PATH=/yaade` when starting the docker container.
