### ISSUE TITLE
Feature request: testing via CLI

### ISSUE THREAD

**Issue by binaryfire** [EsperoTech/yaade#44]
Great work guys! We’ve been looking for an alternative to Hoppscotch (fully self hosted with auth). Just started experimenting with Yaade and it’s looking promising. 

Any plans to add a testing feature? Would be great if we could define tests in the UI and run them via CLI in our CI/CD pipeline

**Comment by jonrosner** [comment]
Thank you for the kind words! Yes, tests are planned. We already added response scripts which will be extended with a testing suite. The question currently is about our favorite syntax flavor. Do you have any opinions on this? Mocha is high on the list right now.

**Comment by binaryfire** [comment]
Nice. I've only just begun to explore API testing so I don't have a preferences. Happy to use whatever you go with.

**Comment by jonrosner** [comment]
We added test support as well as CLI support. You can define a server-side script and execute that script via a curl request now. Check out the nightly container and the docs for more info.
