### ISSUE TITLE
Support for OAuth 2 in Requests for Authentication

### ISSUE THREAD

**Issue by twwd** [EsperoTech/yaade#45]
It would be great if I could specify OAuth 2 options to automatically fetch an access token from an security token service like Keycloak and use it with the `Authorization` header.

E.g., Insomnia has this feature:

![Screen Insomnia OAuth 2](https://user-images.githubusercontent.com/8222565/215450876-e54d158f-7161-4d1b-b8ef-db1f79a2c86f.png)

**Comment by jonrosner** [comment]
Would you prefer that on a request level or rather have it on an environment / collection level?

**Comment by twwd** [comment]
Since I need different clients and partially different grant types/flows (e.g., sometimes _Direct Access Grant_ and sometimes _Authorization Code Flow_), I would prefer on request level. Nevertheless, it would be awesome to specify defaults on environment level.

**Comment by binaryfire** [comment]
Would it be better to have this under an "Authorization" tab with a dropdown to select the method (Bearer, Basic, oAuth2 etc)? That's how Postman, Hoppscotch etc do it. Seems like a more organised approach.

**Comment by jonrosner** [comment]
Authorization tab is now added with `Basic` and `OAuth2` support.
