### ISSUE TITLE
Pre-request script feature

### ISSUE THREAD

**Issue by binaryfire** [EsperoTech/yaade#46]
Hi guys

Any chance of getting a pre-request script feature like Postman? See: https://learning.postman.com/docs/writing-scripts/pre-request-scripts/

This is required for Laravel's session-based Sanctum authentication. See this gist for more details: https://gist.github.com/janzikmund/3047ba4b7031efbabd7ade115f1e3317

**Comment by jonrosner** [comment]
yes, this is definitely planned.

**Comment by jonrosner** [comment]
I am pleased to announce that request scripts are now supported for the Extension proxy. Update the container and the extension to use this new feature.

Check out the docs to see the available functionality: https://docs.yaade.io/scripts.html
