### ISSUE TITLE
Add API Documentation

### ISSUE THREAD

**Issue by alirezaalavi87** [EsperoTech/yaade#48]
Hi.
One thing that this great app is missing for me is API documentation like postman and insomnia have.
Meaning to be able to write documentation for each API and request in yaade.

**Comment by jonrosner** [comment]
Thank you for the comment. This feature is one of the most requested features and will definitely be implemented soon.

Right now the plan is to add a simple Markdown editor / viewer right where the Body Tab Panel is.

**Comment by jonrosner** [comment]
Will close this due to duplication: https://github.com/EsperoTech/yaade/issues/4#issue-1198083042

**Comment by alirezaalavi87** [comment]
Hi, You marked this as completed but I still can't find this feature in the app.

**Comment by jonrosner** [comment]
I marked it because of duplication (look at the comment above). This feature will be added once the new collection view is ready.
