### ISSUE TITLE
Prettify button icon

### ISSUE THREAD

**Issue by alirezaalavi87** [EsperoTech/yaade#49]
At the moment the icon for prettifying the request is a star icon which isn't usually correlated with prettifying code.
I suggest a { } icon which is much more standard and familiar
 
## Current Icon for cleaning code:
![image](https://user-images.githubusercontent.com/63902085/220325217-1c812f9d-96ba-41b0-9f94-7418413fb2f9.png)

## Suggested Icon for cleaning code:
https://icons8.com/icon/122223/curly-brackets

**Comment by alirezaalavi87** [comment]
If the dear maintainer agrees with my statement, I'll happily fix the icon myself.

**Comment by jonrosner** [comment]
Yes I agree. Feel free to change it.
