### ISSUE TITLE
Prettifying the request breaks usage of environment variables

### ISSUE THREAD

**Issue by alirezaalavi87** [EsperoTech/yaade#50]
Hi.
So, using an environment variable in the request body like this:
```
{
    "token": ${token},
    "startRow": 0,
    "dateFilter": "all",
    "data": [{
        "field": "equipmentId",
        "operator": "iContains",
        "value": ["sample"]
    }]
}
```
And after pressing prettify, it looks like this:
```
{
    "token": $ {
        token
    },
    "startRow": 0,
    "dateFilter": "all",
    "data": [{
        "field": "equipmentId",
        "operator": "iContains",
        "value": ["sample"]
    }]
}
```
Which doesn't work anymore.

**Comment by jonrosner** [comment]
Thanks for pointing this out. In your case is the token a number? If it is a string, you can wrap it in `"$token"`

I will try to add a more longterm solution, like special syntax highlighting for these variables.

**Comment by jonrosner** [comment]
We just released an update that handles prettifying JSON with env variables.
