### ISSUE TITLE
Feature request: import Postman collections and environments

### ISSUE THREAD

**Issue by thomascaillier** [EsperoTech/yaade#51]
Hello,

Like Hoppscotch do, that would be a very great feature to import Postman collections and environments from files.
This feature would encourage a lot Postman users to migrate to Yaade (that's my case)

For the implementation, the best would obviously be to integrate this feature to the Yaade UI. 

But, for a quick-win, this functionality could be a side tool to convert postman files to yaade exports. The user could then be able to import converted files in the Yaade UI.

Thanks you guys for your work !

**Comment by jonrosner** [comment]
Thank you for your request. It is indeed possible to import Postman collections. Just create a new collection and choose "Import > Postman"
