### ISSUE TITLE
Environment settings as fixed panel instead of popup

### ISSUE THREAD

**Issue by n14s** [EsperoTech/yaade#59]
When using different environments and their variables extensively, opening the popup and closing it for each variable change hinders the flow a little bit.

Having a (optional) fixed panel for the environment of the current route could be a good idea.

**Comment by jonrosner** [comment]
Thanks for the feedback. Actually, a complete rework of the collection config panel is planned. In the future, we will move away from all the pop-ups and modals and instead use the request/response panel space to display things like collection- and global settings.

**Comment by n14s** [comment]
Sound good!

**Comment by jonrosner** [comment]
This is now released in the newest version.
