### ISSUE TITLE
Add folders to collections for better organisation

### ISSUE THREAD

**Issue by binaryfire** [EsperoTech/yaade#61]
It would be great if we could add folders and sub folders to collections to help keep things organised. Basically the same way Postman does it.

**Comment by Akasiek** [comment]
It's really hard to organise without folders in the long run.

**Comment by BombartSimon** [comment]
+1

**Comment by jonrosner** [comment]
It is now possible to add sub-collections to collections. You can now organize your collections and requests in a folder-like structure. Check out the nightly branch and please report if there are any issues.

**Comment by jonrosner** [comment]
<img width="303" alt="image" src="https://github.com/EsperoTech/yaade/assets/22355732/cdd21e86-c4cd-4303-afa9-bedf971eb305">
