### ISSUE TITLE
unable to authorise via keycloak

### ISSUE THREAD

**Issue by kzachetovb2b** [EsperoTech/yaade#65]
I'm trying to use keycloak as provider with the following configuration

```
{
    "providers": [{
        "id": "b2b",
        "label": "Login with Keycloak",
        "provider": "keycloak",
        "params": {
            "site": "https://url_to_keycloak",
            "clientId": "yaade",
            "clientSecret": "SECRET",
            "callbackUrl": "http://url_to_callback",
            "fields": {
                "username": "/username"
                "groups": "/groups"
            },
            "scopes": ["openid", "email"]
        }
    }]
}
```

but after signing in on keycloak page get this error in web browser:

`{"classLoaderName":null,"moduleName":"java.base","moduleVersion":"11.0.11","methodName":"run","fileName":"Thread.java","lineNumber":829,"className":"java.lang.Thread","nativeMethod":false}],"code":500,"message":"Username not found: /username","suppressed":[],"localizedMessage":"Username not found: /username"}`

yaade launched with 

```
$ docker run -d --restart=always -p 9339:9339 \
    -e YAADE_ADMIN_USERNAME=admin -v yaade:/app/data \
    --name yaade esperotech/yaade:latest
```

there are no revers proxy or any front

in docker log i see these messages

```
[vert.x-eventloop-thread-0] ERROR com.espero.yaade.server.Server - [Thu, 1 Jun 2023 11:44:09 GMT] "GET /api/login?providerid=b2b HTTP_1_1" 500 Username not found: /username "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
[vert.x-eventloop-thread-0] ERROR io.vertx.ext.web.handler.impl.LoggerHandlerImpl - 3.28.85.101 - - [Thu, 1 Jun 2023 11:44:09 GMT] "GET /api/login?providerid=b2b HTTP/1.1" 500 20022 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36"
```

also i have not found any examples with keycloak configuration regarding "fields"

**Comment by jonrosner** [comment]
Can you check if the JWT that Keycloak returns actually contains the field `/username`?

**Comment by jonrosner** [comment]
The following config worked for me using a blank keycloak:

```json
{
    "providers": [{
        "id": "keycloak",
        "label": "Keycloak SSO Login",
        "provider": "keycloak",
        "params": {
            "site": "http://localhost:8080/realms/master",
            "clientId": "myclient",
            "clientSecret": "n0SrjBcU63NURHqfXLaMgDVzPa6GH8Jf",
            "callbackUrl": "http://localhost:9339/keycloak",
            "fields": {
                "username": "/preferred_username",
                "groups": "/groups",
                "defaultGroups": ["test"]
            },
            "scopes": ["openid"]
        }
    }]
}
```

**Comment by kzachetovb2b** [comment]
@jonrosner thank you! 
this config wokrs for me
could you please tell, what url request should i use to check jwt response?

**Comment by jonrosner** [comment]
One way to get a token is to make an admin-cli call towards keycloak. Fortunately you can do this via yaade :) 

URL: http://localhost:8080/realms/master/protocol/openid-connect/token

Headers: content-type: application/x-www-form-urlencoded

Body: client_id=admin-cli&username=admin&grant_type=password&password=admin&scope=offline_access

The resulting call will provide you with an `access_token` that you can now put into a tool like https://jwt.io to inspect.
