### ISSUE TITLE
Login Internal Server Error 

### ISSUE THREAD

**Issue by talenta-eg** [EsperoTech/yaade#66]
<img width="1440" alt="Screenshot 2023-06-12 at 2 01 59 PM" src="https://github.com/EsperoTech/yaade/assets/4216438/162bd9c1-0ece-44c5-9c0f-67a127c260f6">

**Comment by jonrosner** [comment]
Could you explain in more detail the steps to reproduce. this issue?

**Comment by talenta-eg** [comment]
@jonrosner 

i did as following 


`docker volume create yaade`

`docker run -d --restart=always -p 9339:9339 -e admin=admin -v yaade:/app/data --name yaade esperotech/yaade:latest`


Also i have tried health check 


`curl http://localhost:9339/api/health`

Output 

`{"status":"ok","version":"v1"}`
