### ISSUE TITLE
How to add environment variable while using npm ?

### ISSUE THREAD

**Issue by matt734** [EsperoTech/yaade#68]
I am trying to run yaade on my ubuntu machine using npm. I tried setting the env using  export YAADE_ADMIN_USERNAME=admin but I doesn't work. ofc it works while I run it using the executable jar file but when I use npm run dev it doesn't work. what's the workaround for this ?

**Comment by jonrosner** [comment]
You cannot run Yaade exclusively using NPM. NPM can only build and serve the frontend part (static HTML, CSS, JavaScript). To run Yaade you need to:

a) run it as a docker container
b) build a jar using the build script mentioned in the README
c) run it in development mode

If you go for (b) the script will build the frontend, put the static files into the static folder of the server, build the server, and then output a single jar file that you can run normally.


If you go for step (c), then you need to start up all components manually:

1. The server by running the jar (this is where you set YAADE_ADMIN_USERNAME=admin)
2. Frontend by running npm run dev
3. The dev-proxy to connect frontend and backend and to disable CORS

Now you should be able to go to `http://localhost:9337` and login. Note that this should **only be used for development**.

**Comment by matt734** [comment]
> You cannot run Yaade exclusively using NPM. NPM can only build and serve the frontend part (static HTML, CSS, JavaScript). To run Yaade you need to:
> 
> a) run it as a docker container b) build a jar using the build script mentioned in the README c) run it in development mode
> 
> If you go for (b) the script will build the frontend, put the static files into the static folder of the server, build the server, and then output a single jar file that you can run normally.
> 
> If you go for step (c), then you need to start up all components manually:
> 
> 1. The server by running the jar (this is where you set YAADE_ADMIN_USERNAME=admin)
> 2. Frontend by running npm run dev
> 3. The dev-proxy to connect frontend and backend and to disable CORS
> 
> Now you should be able to go to `http://localhost:9337` and login. Note that this should **only be used for development**.

**Comment by matt734** [comment]
I am not sure where I did wrong but I wanted to make some changes in the front end part. I changed the logo on client/src/pages/login/Login.tsx . I am able to see the changes which I made when I run npm run dev but not able to see the changes when I run using the executable jar file

**Comment by jonrosner** [comment]
Yes if you actually want to make changes you need to run the three components in dev mode as I explained above.
