### ISSUE TITLE
Upgrade Password4j

### ISSUE THREAD

**Issue by firaja** [EsperoTech/yaade#80]
Hello team,

creator of [Password4j](https://github.com/Password4j/password4j) here.

I've created a PR to upgrade Password4j from 1.5.4 to 1.7.1 maintaining backward compatibility with the hashes produced so far.

In general it's better to always specify the parameters of Argon2 (or any other algorithm) in the code or in a properties file, like I did in my PR. In 1.6.1 the implicit configurations were changed in order to fit OWASP's minimum security requirements and without the properties file you would had inconsistencies.

Enjoy 🚀

**Comment by jonrosner** [comment]
Thank you for upgrading!
