### ISSUE TITLE
Feature Request: Duplicate collections

### ISSUE THREAD

**Issue by mgmorcos** [EsperoTech/yaade#89]
Currently, in order to duplicate a full collection, you would need to create the new collection and duplicate/move each request from the old collection.

**Comment by jonrosner** [comment]
Noted. Will be added in a future version

**Comment by mgmorcos** [comment]
🙏 🙌

**Comment by jonrosner** [comment]
This has been merged and released into the nightly branch. Will be released to latest in about a week.
