### ISSUE TITLE
Bug: Setting body application/json always sends text/plain

### ISSUE THREAD

**Issue by Zakay** [EsperoTech/yaade#95]
<img width="550" alt="image" src="https://github.com/EsperoTech/yaade/assets/315159/a0c9b190-3763-4c2e-a485-f4c15189e2da">
<img width="320" alt="image" src="https://github.com/EsperoTech/yaade/assets/315159/8fcf1636-7122-456e-a491-c384ff3f9d87">

**Comment by jonrosner** [comment]
This box is only for formatting. If you want to send the header, add it as a header `Content-Type: application/json`
