### ISSUE TITLE
Option for disable SSL check

### ISSUE THREAD

**Issue by Chouclent** [EsperoTech/yaade#96]
Hello Contributors,

Nice work on this application, We’ve been looking for an alternative to Hoppscotch (fully self hosted with auth).
Is there an option to disable ssl verification?
If you can't add a certificate library. 

I currently use an internal certificate for API development. And I get the message 'Failed to create SSL connection' during a request.

Thanks.

**Comment by jonrosner** [comment]
Hello,

Thanks for trying out Yaade. 

What proxy are you using when doing the request? Extension or server?

**Comment by jonrosner** [comment]
Thanks. This is configurable in the vert.x web client. I'll add it to the changelog of the next release.

**Comment by SeptianENC** [comment]
hello @jonrosner is this feature was release in the latest yaade? if yes, how i can use that? i can't find in the documentation about ssl check. thank you

**Comment by jonrosner** [comment]
Hello, not yet, but will be prioritized.

**Comment by jonrosner** [comment]
added and pushed to the nightly build. You can test it already by pulling the nightly container `yaade:nightly`

Will be released to the latest build soon.

**Comment by alexk7110** [comment]
It works great, just FYI I had to uncheck 'Disable "Verify Host"' AND check the 'Trust All' toggle for it to work.

**Comment by jonrosner** [comment]
yes, that is expected! Thanks for testing it out
