### ISSUE TITLE
Feature Request: Structured data support (multipart/form-data)

### ISSUE THREAD

**Issue by robinwesterik** [EsperoTech/yaade#97]
Multipart requests are most commonly used to upload files and data to a server. OpenAPI, Postman, and Hoppscotch all have full support for these type of requests.

In order for our team to fully move over to Yaade, we would appreciate it if structured data can be added in the near future as a body type.

**Comment by jonrosner** [comment]
What do you mean with full support? Are you talking about editor highlighting or do you want to upload files via Yaade?

**Comment by robinwesterik** [comment]
I'd like to upload files and add text to a multipart form via Yaade, as is possible with alternatives like Insomnia and Hoppscotch (see screenshots)
![image](https://github.com/EsperoTech/yaade/assets/64894343/c66e97e1-53d0-4a28-9355-9cac8b4b1454)
![image](https://github.com/EsperoTech/yaade/assets/64894343/af8061c7-a441-4155-b646-f334e80f6455)

**Comment by jonrosner** [comment]
multipart/form-data and file uploads is now supported.
